Repository what-is-the-clean/Study-Clean-Code, pull requests merged in 2023-08, with the labels that each got.

#2 클린코드 1 ~ 3 장과 6장에 대한 학습 내용 정리
  Chapter 01~05. Convention/chanhyeoKing/Chapter2.md
  Chapter 01~05. Convention/chanhyeoKing/Chapter3.md
  Chapter 01~05. Convention/chanhyeoKing/Introduce-Chapter1.md
  Chapter 06. Objects and Data Structures/chanhyeoKing/Chapter6.md
Labels: documentation, week1, HyeoKing

#3 6장 스터디내용
  Chapter 06. Objects and Data Structures/arthur/index.md
Labels: documentation, week1

#4 Chapter 06. Objects and Data Structures
  Chapter 06. Objects and Data Structures/.gitkeep
  Chapter 06. Objects and Data Structures/zin.md
Labels: documentation, zin, week1

#5 6장 정리
  Chapter 06. Objects and Data Structures/summary.md
Labels: documentation, week1

#7 week1 - ChanHyeok
  Chapter 01~05. Convention/chanhyeoKing/Chapter2.md
  Chapter 01~05. Convention/chanhyeoKing/Chapter3.md
  Chapter 01~05. Convention/chanhyeoKing/Introduce-Chapter1.md
  Chapter 06. Objects and Data Structures/chanhyeoKing/Chapter6.md
Labels: merge

#8 week1 - Zin
  Chapter 06. Objects and Data Structures/.gitkeep
  Chapter 06. Objects and Data Structures/zin.md
Labels: merge

#9 week1 - JaeWon
  Chapter 06. Objects and Data Structures/summary.md
Labels: merge
